### ISSUE TITLE
bug: AttributeError: 'dict' object has no attribute 'link_titles'

### ISSUE THREAD

**Issue by glennmatthews** [mkdocstrings/autorefs#68]
### Description of the bug

Readthedocs build using `mkdocs` is failing with 1.4.0:

```
python -m mkdocs build --clean --site-dir $READTHEDOCS_OUTPUT/html --config-file mkdocs.yml 
...
    if self.config.link_titles == "auto":
AttributeError: 'dict' object has no attribute 'link_titles'
```

### To Reproduce

AFAIK we don't have any custom configuration for this package in our `mkdocs.yml`.

### Full traceback

```python
python -m mkdocs build --clean --site-dir $READTHEDOCS_OUTPUT/html --config-file mkdocs.yml 

Traceback (most recent call last):
  File "/home/docs/.asdf/installs/python/3.9.20/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/docs/.asdf/installs/python/3.9.20/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/nautobot/envs/6898/lib/python3.9/site-packages/mkdocs/__main__.py", line 366, in <module>
    cli()
  File "/home/docs/checkouts/readthedocs.org/user_builds/nautobot/envs/6898/lib/python3.9/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/nautobot/envs/6898/lib/python3.9/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/home/docs/checkouts/readthedocs.org/user_builds/nautobot/envs/6898/lib/python3.9/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/docs/checkouts/readthedocs.org/user_builds/nautobot/envs/6898/lib/python3.9/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/docs/checkouts/readthedocs.org/user_builds/nautobot/envs/6898/lib/python3.9/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/nautobot/envs/6898/lib/python3.9/site-packages/mkdocs/__main__.py", line 284, in build_command
    build.build(cfg, dirty=not clean)
  File "/home/docs/checkouts/readthedocs.org/user_builds/nautobot/envs/6898/lib/python3.9/site-packages/mkdocs/commands/build.py", line 265, in build
    config = config.plugins.on_config(config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/nautobot/envs/6898/lib/python3.9/site-packages/mkdocs/plugins.py", line 587, in on_config
    return self.run_event('config', config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/nautobot/envs/6898/lib/python3.9/site-packages/mkdocs/plugins.py", line 566, in run_event
    result = method(item, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/nautobot/envs/6898/lib/python3.9/site-packages/mkdocs_autorefs/_internal/plugin.py", line 180, in on_config
    if self.config.link_titles == "auto":
AttributeError: 'dict' object has no attribute 'link_titles'
```

</details>

### Environment information

```bash
python -m mkdocs_autorefs._internal.debug  # | xclip -selection clipboard
```

PASTE MARKDOWN OUTPUT HERE

**Comment by vvmruder** [comment]
I do have the same problem. Readthedocs build using `mkdocs` is failing with 1.4.0. It came out of nothing. Quickly tried with older 1.3.1 and there it works.

**Comment by pawamoy** [comment]
No amount of testing will ever save me from breaking builds... 🙉 

Sorry for the trouble, and thanks for reporting quickly. Investigating!

**Comment by vvmruder** [comment]
Thx for hooking onto that so quickly. In my case its mkdocs 1.6.1

**Comment by pawamoy** [comment]
Thanks. It's because of mkdocstrings pre-0.26.1: https://mkdocstrings.github.io/changelog/#bug-fixes_2.

**Comment by vvmruder** [comment]
@pawamoy I can confirm, that it is working as you described.
