### ISSUE TITLE
bug: Error when updating to 1.4.0

### ISSUE THREAD

**Issue by cpfarrell** [mkdocstrings/autorefs#69]
### Description of the bug
When I attempt to update to library version 1.4.0 I'm seeing an error stating `AttributeError: 'dict' object has no attribute 'link_titles'`. Using 1.3.1 removes the error

### To Reproduce
I unfortunately don't have a minimally reproducible example at the moment but could try to create one.

### Full traceback
```python
DEBUG   -  Running `config` event from plugin 'autorefs'
DEBUG   -  mkdocs_autorefs: Adding AutorefsExtension to the list
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/project-bkExcudj-py3.9/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/root/.cache/pypoetry/virtualenvs/project-bkExcudj-py3.9/lib/python3.9/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/project-bkExcudj-py3.9/lib/python3.9/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/root/.cache/pypoetry/virtualenvs/project-bkExcudj-py3.9/lib/python3.9/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.cache/pypoetry/virtualenvs/project-bkExcudj-py3.9/lib/python3.9/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.cache/pypoetry/virtualenvs/project-bkExcudj-py3.9/lib/python3.9/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/project-bkExcudj-py3.9/lib/python3.9/site-packages/mkdocs/__main__.py", line 288, in build_command
    build.build(cfg, dirty=not clean)
  File "/root/.cache/pypoetry/virtualenvs/project-bkExcudj-py3.9/lib/python3.9/site-packages/mkdocs/commands/build.py", line 265, in build
    config = config.plugins.on_config(config)
  File "/root/.cache/pypoetry/virtualenvs/project-bkExcudj-py3.9/lib/python3.9/site-packages/mkdocs/plugins.py", line 587, in on_config
    return self.run_event('config', config)
  File "/root/.cache/pypoetry/virtualenvs/project-bkExcudj-py3.9/lib/python3.9/site-packages/mkdocs/plugins.py", line 566, in run_event
    result = method(item, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/project-bkExcudj-py3.9/lib/python3.9/site-packages/mkdocs_autorefs/_internal/plugin.py", line 180, in on_config
    if self.config.link_titles == "auto":
AttributeError: 'dict' object has no attribute 'link_titles'
```

</details>

### Expected behavior
Not have build error

### Environment information

```bash
python -m mkdocs_autorefs._internal.debug  # | xclip -selection clipboard
```

```
- __System__: macOS-15.3.1-arm64-arm-64bit
- __Python__: cpython 3.9.19 (/Users/cfarrell/Development/project/.venv/bin/python)
- __Environment variables__:
- __Installed packages__:
  - `mkdocs-autorefs` v1.4.1
```

### Additional context
Similar seen here https://github.com/stanford-crfm/helm/issues/3393

**Comment by pawamoy** [comment]
Hello @cpfarrell, thanks for the report 🙂 I believe this is a duplicate of https://github.com/mkdocstrings/autorefs/issues/68. Could you check and let me know if the solution mentioned in #68 works for you?

**Comment by cpfarrell** [comment]
Yers, that fixed it. Thanks for fix and sorry for not seeing that other issue
